name: pokemon_search
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  flutter_bloc: ^6.0.0
  equatable: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.3.0

flutter_native_splash:
  color: "#e0a604"
  image: assets/ion-removebg-preview.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/pikachu_splash_screen.png